package com.mengka.springboot.dao.domain;

import java.io.Serializable;

public class GogsRepositoryDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.owner_id
     *
     * @mbg.generated
     */
    private Long ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.lower_name
     *
     * @mbg.generated
     */
    private String lowerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.website
     *
     * @mbg.generated
     */
    private String website;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.default_branch
     *
     * @mbg.generated
     */
    private String defaultBranch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.size
     *
     * @mbg.generated
     */
    private Long size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.use_custom_avatar
     *
     * @mbg.generated
     */
    private Boolean useCustomAvatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.num_watches
     *
     * @mbg.generated
     */
    private Integer numWatches;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.num_stars
     *
     * @mbg.generated
     */
    private Integer numStars;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.num_forks
     *
     * @mbg.generated
     */
    private Integer numForks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.num_issues
     *
     * @mbg.generated
     */
    private Integer numIssues;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.num_closed_issues
     *
     * @mbg.generated
     */
    private Integer numClosedIssues;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.num_pulls
     *
     * @mbg.generated
     */
    private Integer numPulls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.num_closed_pulls
     *
     * @mbg.generated
     */
    private Integer numClosedPulls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.num_milestones
     *
     * @mbg.generated
     */
    private Integer numMilestones;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.num_closed_milestones
     *
     * @mbg.generated
     */
    private Integer numClosedMilestones;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.is_private
     *
     * @mbg.generated
     */
    private Boolean isPrivate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.is_bare
     *
     * @mbg.generated
     */
    private Boolean isBare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.is_mirror
     *
     * @mbg.generated
     */
    private Boolean isMirror;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.enable_wiki
     *
     * @mbg.generated
     */
    private Boolean enableWiki;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.allow_public_wiki
     *
     * @mbg.generated
     */
    private Boolean allowPublicWiki;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.enable_external_wiki
     *
     * @mbg.generated
     */
    private Boolean enableExternalWiki;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.external_wiki_url
     *
     * @mbg.generated
     */
    private String externalWikiUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.enable_issues
     *
     * @mbg.generated
     */
    private Boolean enableIssues;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.allow_public_issues
     *
     * @mbg.generated
     */
    private Boolean allowPublicIssues;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.enable_external_tracker
     *
     * @mbg.generated
     */
    private Boolean enableExternalTracker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.external_tracker_url
     *
     * @mbg.generated
     */
    private String externalTrackerUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.external_tracker_format
     *
     * @mbg.generated
     */
    private String externalTrackerFormat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.external_tracker_style
     *
     * @mbg.generated
     */
    private String externalTrackerStyle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.enable_pulls
     *
     * @mbg.generated
     */
    private Boolean enablePulls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.pulls_ignore_whitespace
     *
     * @mbg.generated
     */
    private Boolean pullsIgnoreWhitespace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.pulls_allow_rebase
     *
     * @mbg.generated
     */
    private Boolean pullsAllowRebase;

    private Boolean hasChild;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.is_fork
     *
     * @mbg.generated
     */
    private Boolean isFork;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.fork_id
     *
     * @mbg.generated
     */
    private Long forkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.created_unix
     *
     * @mbg.generated
     */
    private Long createdUnix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.updated_unix
     *
     * @mbg.generated
     */
    private Long updatedUnix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table repository
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.id
     *
     * @return the value of repository.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.id
     *
     * @param id the value for repository.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.owner_id
     *
     * @return the value of repository.owner_id
     *
     * @mbg.generated
     */
    public Long getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.owner_id
     *
     * @param ownerId the value for repository.owner_id
     *
     * @mbg.generated
     */
    public void setOwnerId(Long ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.lower_name
     *
     * @return the value of repository.lower_name
     *
     * @mbg.generated
     */
    public String getLowerName() {
        return lowerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.lower_name
     *
     * @param lowerName the value for repository.lower_name
     *
     * @mbg.generated
     */
    public void setLowerName(String lowerName) {
        this.lowerName = lowerName == null ? null : lowerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.name
     *
     * @return the value of repository.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.name
     *
     * @param name the value for repository.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.description
     *
     * @return the value of repository.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.description
     *
     * @param description the value for repository.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.website
     *
     * @return the value of repository.website
     *
     * @mbg.generated
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.website
     *
     * @param website the value for repository.website
     *
     * @mbg.generated
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.default_branch
     *
     * @return the value of repository.default_branch
     *
     * @mbg.generated
     */
    public String getDefaultBranch() {
        return defaultBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.default_branch
     *
     * @param defaultBranch the value for repository.default_branch
     *
     * @mbg.generated
     */
    public void setDefaultBranch(String defaultBranch) {
        this.defaultBranch = defaultBranch == null ? null : defaultBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.size
     *
     * @return the value of repository.size
     *
     * @mbg.generated
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.size
     *
     * @param size the value for repository.size
     *
     * @mbg.generated
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.use_custom_avatar
     *
     * @return the value of repository.use_custom_avatar
     *
     * @mbg.generated
     */
    public Boolean getUseCustomAvatar() {
        return useCustomAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.use_custom_avatar
     *
     * @param useCustomAvatar the value for repository.use_custom_avatar
     *
     * @mbg.generated
     */
    public void setUseCustomAvatar(Boolean useCustomAvatar) {
        this.useCustomAvatar = useCustomAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.num_watches
     *
     * @return the value of repository.num_watches
     *
     * @mbg.generated
     */
    public Integer getNumWatches() {
        return numWatches;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.num_watches
     *
     * @param numWatches the value for repository.num_watches
     *
     * @mbg.generated
     */
    public void setNumWatches(Integer numWatches) {
        this.numWatches = numWatches;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.num_stars
     *
     * @return the value of repository.num_stars
     *
     * @mbg.generated
     */
    public Integer getNumStars() {
        return numStars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.num_stars
     *
     * @param numStars the value for repository.num_stars
     *
     * @mbg.generated
     */
    public void setNumStars(Integer numStars) {
        this.numStars = numStars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.num_forks
     *
     * @return the value of repository.num_forks
     *
     * @mbg.generated
     */
    public Integer getNumForks() {
        return numForks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.num_forks
     *
     * @param numForks the value for repository.num_forks
     *
     * @mbg.generated
     */
    public void setNumForks(Integer numForks) {
        this.numForks = numForks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.num_issues
     *
     * @return the value of repository.num_issues
     *
     * @mbg.generated
     */
    public Integer getNumIssues() {
        return numIssues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.num_issues
     *
     * @param numIssues the value for repository.num_issues
     *
     * @mbg.generated
     */
    public void setNumIssues(Integer numIssues) {
        this.numIssues = numIssues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.num_closed_issues
     *
     * @return the value of repository.num_closed_issues
     *
     * @mbg.generated
     */
    public Integer getNumClosedIssues() {
        return numClosedIssues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.num_closed_issues
     *
     * @param numClosedIssues the value for repository.num_closed_issues
     *
     * @mbg.generated
     */
    public void setNumClosedIssues(Integer numClosedIssues) {
        this.numClosedIssues = numClosedIssues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.num_pulls
     *
     * @return the value of repository.num_pulls
     *
     * @mbg.generated
     */
    public Integer getNumPulls() {
        return numPulls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.num_pulls
     *
     * @param numPulls the value for repository.num_pulls
     *
     * @mbg.generated
     */
    public void setNumPulls(Integer numPulls) {
        this.numPulls = numPulls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.num_closed_pulls
     *
     * @return the value of repository.num_closed_pulls
     *
     * @mbg.generated
     */
    public Integer getNumClosedPulls() {
        return numClosedPulls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.num_closed_pulls
     *
     * @param numClosedPulls the value for repository.num_closed_pulls
     *
     * @mbg.generated
     */
    public void setNumClosedPulls(Integer numClosedPulls) {
        this.numClosedPulls = numClosedPulls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.num_milestones
     *
     * @return the value of repository.num_milestones
     *
     * @mbg.generated
     */
    public Integer getNumMilestones() {
        return numMilestones;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.num_milestones
     *
     * @param numMilestones the value for repository.num_milestones
     *
     * @mbg.generated
     */
    public void setNumMilestones(Integer numMilestones) {
        this.numMilestones = numMilestones;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.num_closed_milestones
     *
     * @return the value of repository.num_closed_milestones
     *
     * @mbg.generated
     */
    public Integer getNumClosedMilestones() {
        return numClosedMilestones;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.num_closed_milestones
     *
     * @param numClosedMilestones the value for repository.num_closed_milestones
     *
     * @mbg.generated
     */
    public void setNumClosedMilestones(Integer numClosedMilestones) {
        this.numClosedMilestones = numClosedMilestones;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.is_private
     *
     * @return the value of repository.is_private
     *
     * @mbg.generated
     */
    public Boolean getIsPrivate() {
        return isPrivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.is_private
     *
     * @param isPrivate the value for repository.is_private
     *
     * @mbg.generated
     */
    public void setIsPrivate(Boolean isPrivate) {
        this.isPrivate = isPrivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.is_bare
     *
     * @return the value of repository.is_bare
     *
     * @mbg.generated
     */
    public Boolean getIsBare() {
        return isBare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.is_bare
     *
     * @param isBare the value for repository.is_bare
     *
     * @mbg.generated
     */
    public void setIsBare(Boolean isBare) {
        this.isBare = isBare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.is_mirror
     *
     * @return the value of repository.is_mirror
     *
     * @mbg.generated
     */
    public Boolean getIsMirror() {
        return isMirror;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.is_mirror
     *
     * @param isMirror the value for repository.is_mirror
     *
     * @mbg.generated
     */
    public void setIsMirror(Boolean isMirror) {
        this.isMirror = isMirror;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.enable_wiki
     *
     * @return the value of repository.enable_wiki
     *
     * @mbg.generated
     */
    public Boolean getEnableWiki() {
        return enableWiki;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.enable_wiki
     *
     * @param enableWiki the value for repository.enable_wiki
     *
     * @mbg.generated
     */
    public void setEnableWiki(Boolean enableWiki) {
        this.enableWiki = enableWiki;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.allow_public_wiki
     *
     * @return the value of repository.allow_public_wiki
     *
     * @mbg.generated
     */
    public Boolean getAllowPublicWiki() {
        return allowPublicWiki;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.allow_public_wiki
     *
     * @param allowPublicWiki the value for repository.allow_public_wiki
     *
     * @mbg.generated
     */
    public void setAllowPublicWiki(Boolean allowPublicWiki) {
        this.allowPublicWiki = allowPublicWiki;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.enable_external_wiki
     *
     * @return the value of repository.enable_external_wiki
     *
     * @mbg.generated
     */
    public Boolean getEnableExternalWiki() {
        return enableExternalWiki;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.enable_external_wiki
     *
     * @param enableExternalWiki the value for repository.enable_external_wiki
     *
     * @mbg.generated
     */
    public void setEnableExternalWiki(Boolean enableExternalWiki) {
        this.enableExternalWiki = enableExternalWiki;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.external_wiki_url
     *
     * @return the value of repository.external_wiki_url
     *
     * @mbg.generated
     */
    public String getExternalWikiUrl() {
        return externalWikiUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.external_wiki_url
     *
     * @param externalWikiUrl the value for repository.external_wiki_url
     *
     * @mbg.generated
     */
    public void setExternalWikiUrl(String externalWikiUrl) {
        this.externalWikiUrl = externalWikiUrl == null ? null : externalWikiUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.enable_issues
     *
     * @return the value of repository.enable_issues
     *
     * @mbg.generated
     */
    public Boolean getEnableIssues() {
        return enableIssues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.enable_issues
     *
     * @param enableIssues the value for repository.enable_issues
     *
     * @mbg.generated
     */
    public void setEnableIssues(Boolean enableIssues) {
        this.enableIssues = enableIssues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.allow_public_issues
     *
     * @return the value of repository.allow_public_issues
     *
     * @mbg.generated
     */
    public Boolean getAllowPublicIssues() {
        return allowPublicIssues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.allow_public_issues
     *
     * @param allowPublicIssues the value for repository.allow_public_issues
     *
     * @mbg.generated
     */
    public void setAllowPublicIssues(Boolean allowPublicIssues) {
        this.allowPublicIssues = allowPublicIssues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.enable_external_tracker
     *
     * @return the value of repository.enable_external_tracker
     *
     * @mbg.generated
     */
    public Boolean getEnableExternalTracker() {
        return enableExternalTracker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.enable_external_tracker
     *
     * @param enableExternalTracker the value for repository.enable_external_tracker
     *
     * @mbg.generated
     */
    public void setEnableExternalTracker(Boolean enableExternalTracker) {
        this.enableExternalTracker = enableExternalTracker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.external_tracker_url
     *
     * @return the value of repository.external_tracker_url
     *
     * @mbg.generated
     */
    public String getExternalTrackerUrl() {
        return externalTrackerUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.external_tracker_url
     *
     * @param externalTrackerUrl the value for repository.external_tracker_url
     *
     * @mbg.generated
     */
    public void setExternalTrackerUrl(String externalTrackerUrl) {
        this.externalTrackerUrl = externalTrackerUrl == null ? null : externalTrackerUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.external_tracker_format
     *
     * @return the value of repository.external_tracker_format
     *
     * @mbg.generated
     */
    public String getExternalTrackerFormat() {
        return externalTrackerFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.external_tracker_format
     *
     * @param externalTrackerFormat the value for repository.external_tracker_format
     *
     * @mbg.generated
     */
    public void setExternalTrackerFormat(String externalTrackerFormat) {
        this.externalTrackerFormat = externalTrackerFormat == null ? null : externalTrackerFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.external_tracker_style
     *
     * @return the value of repository.external_tracker_style
     *
     * @mbg.generated
     */
    public String getExternalTrackerStyle() {
        return externalTrackerStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.external_tracker_style
     *
     * @param externalTrackerStyle the value for repository.external_tracker_style
     *
     * @mbg.generated
     */
    public void setExternalTrackerStyle(String externalTrackerStyle) {
        this.externalTrackerStyle = externalTrackerStyle == null ? null : externalTrackerStyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.enable_pulls
     *
     * @return the value of repository.enable_pulls
     *
     * @mbg.generated
     */
    public Boolean getEnablePulls() {
        return enablePulls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.enable_pulls
     *
     * @param enablePulls the value for repository.enable_pulls
     *
     * @mbg.generated
     */
    public void setEnablePulls(Boolean enablePulls) {
        this.enablePulls = enablePulls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.pulls_ignore_whitespace
     *
     * @return the value of repository.pulls_ignore_whitespace
     *
     * @mbg.generated
     */
    public Boolean getPullsIgnoreWhitespace() {
        return pullsIgnoreWhitespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.pulls_ignore_whitespace
     *
     * @param pullsIgnoreWhitespace the value for repository.pulls_ignore_whitespace
     *
     * @mbg.generated
     */
    public void setPullsIgnoreWhitespace(Boolean pullsIgnoreWhitespace) {
        this.pullsIgnoreWhitespace = pullsIgnoreWhitespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.pulls_allow_rebase
     *
     * @return the value of repository.pulls_allow_rebase
     *
     * @mbg.generated
     */
    public Boolean getPullsAllowRebase() {
        return pullsAllowRebase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.pulls_allow_rebase
     *
     * @param pullsAllowRebase the value for repository.pulls_allow_rebase
     *
     * @mbg.generated
     */
    public void setPullsAllowRebase(Boolean pullsAllowRebase) {
        this.pullsAllowRebase = pullsAllowRebase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.is_fork
     *
     * @return the value of repository.is_fork
     *
     * @mbg.generated
     */
    public Boolean getIsFork() {
        return isFork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.is_fork
     *
     * @param isFork the value for repository.is_fork
     *
     * @mbg.generated
     */
    public void setIsFork(Boolean isFork) {
        this.isFork = isFork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.fork_id
     *
     * @return the value of repository.fork_id
     *
     * @mbg.generated
     */
    public Long getForkId() {
        return forkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.fork_id
     *
     * @param forkId the value for repository.fork_id
     *
     * @mbg.generated
     */
    public void setForkId(Long forkId) {
        this.forkId = forkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.created_unix
     *
     * @return the value of repository.created_unix
     *
     * @mbg.generated
     */
    public Long getCreatedUnix() {
        return createdUnix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.created_unix
     *
     * @param createdUnix the value for repository.created_unix
     *
     * @mbg.generated
     */
    public void setCreatedUnix(Long createdUnix) {
        this.createdUnix = createdUnix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.updated_unix
     *
     * @return the value of repository.updated_unix
     *
     * @mbg.generated
     */
    public Long getUpdatedUnix() {
        return updatedUnix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.updated_unix
     *
     * @param updatedUnix the value for repository.updated_unix
     *
     * @mbg.generated
     */
    public void setUpdatedUnix(Long updatedUnix) {
        this.updatedUnix = updatedUnix;
    }

    public Boolean getHasChild() {
        return hasChild;
    }

    public void setHasChild(Boolean hasChild) {
        this.hasChild = hasChild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GogsRepositoryDO other = (GogsRepositoryDO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOwnerId() == null ? other.getOwnerId() == null : this.getOwnerId().equals(other.getOwnerId()))
            && (this.getLowerName() == null ? other.getLowerName() == null : this.getLowerName().equals(other.getLowerName()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getWebsite() == null ? other.getWebsite() == null : this.getWebsite().equals(other.getWebsite()))
            && (this.getDefaultBranch() == null ? other.getDefaultBranch() == null : this.getDefaultBranch().equals(other.getDefaultBranch()))
            && (this.getSize() == null ? other.getSize() == null : this.getSize().equals(other.getSize()))
            && (this.getUseCustomAvatar() == null ? other.getUseCustomAvatar() == null : this.getUseCustomAvatar().equals(other.getUseCustomAvatar()))
            && (this.getNumWatches() == null ? other.getNumWatches() == null : this.getNumWatches().equals(other.getNumWatches()))
            && (this.getNumStars() == null ? other.getNumStars() == null : this.getNumStars().equals(other.getNumStars()))
            && (this.getNumForks() == null ? other.getNumForks() == null : this.getNumForks().equals(other.getNumForks()))
            && (this.getNumIssues() == null ? other.getNumIssues() == null : this.getNumIssues().equals(other.getNumIssues()))
            && (this.getNumClosedIssues() == null ? other.getNumClosedIssues() == null : this.getNumClosedIssues().equals(other.getNumClosedIssues()))
            && (this.getNumPulls() == null ? other.getNumPulls() == null : this.getNumPulls().equals(other.getNumPulls()))
            && (this.getNumClosedPulls() == null ? other.getNumClosedPulls() == null : this.getNumClosedPulls().equals(other.getNumClosedPulls()))
            && (this.getNumMilestones() == null ? other.getNumMilestones() == null : this.getNumMilestones().equals(other.getNumMilestones()))
            && (this.getNumClosedMilestones() == null ? other.getNumClosedMilestones() == null : this.getNumClosedMilestones().equals(other.getNumClosedMilestones()))
            && (this.getIsPrivate() == null ? other.getIsPrivate() == null : this.getIsPrivate().equals(other.getIsPrivate()))
            && (this.getIsBare() == null ? other.getIsBare() == null : this.getIsBare().equals(other.getIsBare()))
            && (this.getIsMirror() == null ? other.getIsMirror() == null : this.getIsMirror().equals(other.getIsMirror()))
            && (this.getEnableWiki() == null ? other.getEnableWiki() == null : this.getEnableWiki().equals(other.getEnableWiki()))
            && (this.getAllowPublicWiki() == null ? other.getAllowPublicWiki() == null : this.getAllowPublicWiki().equals(other.getAllowPublicWiki()))
            && (this.getEnableExternalWiki() == null ? other.getEnableExternalWiki() == null : this.getEnableExternalWiki().equals(other.getEnableExternalWiki()))
            && (this.getExternalWikiUrl() == null ? other.getExternalWikiUrl() == null : this.getExternalWikiUrl().equals(other.getExternalWikiUrl()))
            && (this.getEnableIssues() == null ? other.getEnableIssues() == null : this.getEnableIssues().equals(other.getEnableIssues()))
            && (this.getAllowPublicIssues() == null ? other.getAllowPublicIssues() == null : this.getAllowPublicIssues().equals(other.getAllowPublicIssues()))
            && (this.getEnableExternalTracker() == null ? other.getEnableExternalTracker() == null : this.getEnableExternalTracker().equals(other.getEnableExternalTracker()))
            && (this.getExternalTrackerUrl() == null ? other.getExternalTrackerUrl() == null : this.getExternalTrackerUrl().equals(other.getExternalTrackerUrl()))
            && (this.getExternalTrackerFormat() == null ? other.getExternalTrackerFormat() == null : this.getExternalTrackerFormat().equals(other.getExternalTrackerFormat()))
            && (this.getExternalTrackerStyle() == null ? other.getExternalTrackerStyle() == null : this.getExternalTrackerStyle().equals(other.getExternalTrackerStyle()))
            && (this.getEnablePulls() == null ? other.getEnablePulls() == null : this.getEnablePulls().equals(other.getEnablePulls()))
            && (this.getPullsIgnoreWhitespace() == null ? other.getPullsIgnoreWhitespace() == null : this.getPullsIgnoreWhitespace().equals(other.getPullsIgnoreWhitespace()))
            && (this.getPullsAllowRebase() == null ? other.getPullsAllowRebase() == null : this.getPullsAllowRebase().equals(other.getPullsAllowRebase()))
            && (this.getIsFork() == null ? other.getIsFork() == null : this.getIsFork().equals(other.getIsFork()))
            && (this.getForkId() == null ? other.getForkId() == null : this.getForkId().equals(other.getForkId()))
            && (this.getCreatedUnix() == null ? other.getCreatedUnix() == null : this.getCreatedUnix().equals(other.getCreatedUnix()))
            && (this.getUpdatedUnix() == null ? other.getUpdatedUnix() == null : this.getUpdatedUnix().equals(other.getUpdatedUnix()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOwnerId() == null) ? 0 : getOwnerId().hashCode());
        result = prime * result + ((getLowerName() == null) ? 0 : getLowerName().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getWebsite() == null) ? 0 : getWebsite().hashCode());
        result = prime * result + ((getDefaultBranch() == null) ? 0 : getDefaultBranch().hashCode());
        result = prime * result + ((getSize() == null) ? 0 : getSize().hashCode());
        result = prime * result + ((getUseCustomAvatar() == null) ? 0 : getUseCustomAvatar().hashCode());
        result = prime * result + ((getNumWatches() == null) ? 0 : getNumWatches().hashCode());
        result = prime * result + ((getNumStars() == null) ? 0 : getNumStars().hashCode());
        result = prime * result + ((getNumForks() == null) ? 0 : getNumForks().hashCode());
        result = prime * result + ((getNumIssues() == null) ? 0 : getNumIssues().hashCode());
        result = prime * result + ((getNumClosedIssues() == null) ? 0 : getNumClosedIssues().hashCode());
        result = prime * result + ((getNumPulls() == null) ? 0 : getNumPulls().hashCode());
        result = prime * result + ((getNumClosedPulls() == null) ? 0 : getNumClosedPulls().hashCode());
        result = prime * result + ((getNumMilestones() == null) ? 0 : getNumMilestones().hashCode());
        result = prime * result + ((getNumClosedMilestones() == null) ? 0 : getNumClosedMilestones().hashCode());
        result = prime * result + ((getIsPrivate() == null) ? 0 : getIsPrivate().hashCode());
        result = prime * result + ((getIsBare() == null) ? 0 : getIsBare().hashCode());
        result = prime * result + ((getIsMirror() == null) ? 0 : getIsMirror().hashCode());
        result = prime * result + ((getEnableWiki() == null) ? 0 : getEnableWiki().hashCode());
        result = prime * result + ((getAllowPublicWiki() == null) ? 0 : getAllowPublicWiki().hashCode());
        result = prime * result + ((getEnableExternalWiki() == null) ? 0 : getEnableExternalWiki().hashCode());
        result = prime * result + ((getExternalWikiUrl() == null) ? 0 : getExternalWikiUrl().hashCode());
        result = prime * result + ((getEnableIssues() == null) ? 0 : getEnableIssues().hashCode());
        result = prime * result + ((getAllowPublicIssues() == null) ? 0 : getAllowPublicIssues().hashCode());
        result = prime * result + ((getEnableExternalTracker() == null) ? 0 : getEnableExternalTracker().hashCode());
        result = prime * result + ((getExternalTrackerUrl() == null) ? 0 : getExternalTrackerUrl().hashCode());
        result = prime * result + ((getExternalTrackerFormat() == null) ? 0 : getExternalTrackerFormat().hashCode());
        result = prime * result + ((getExternalTrackerStyle() == null) ? 0 : getExternalTrackerStyle().hashCode());
        result = prime * result + ((getEnablePulls() == null) ? 0 : getEnablePulls().hashCode());
        result = prime * result + ((getPullsIgnoreWhitespace() == null) ? 0 : getPullsIgnoreWhitespace().hashCode());
        result = prime * result + ((getPullsAllowRebase() == null) ? 0 : getPullsAllowRebase().hashCode());
        result = prime * result + ((getIsFork() == null) ? 0 : getIsFork().hashCode());
        result = prime * result + ((getForkId() == null) ? 0 : getForkId().hashCode());
        result = prime * result + ((getCreatedUnix() == null) ? 0 : getCreatedUnix().hashCode());
        result = prime * result + ((getUpdatedUnix() == null) ? 0 : getUpdatedUnix().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", ownerId=").append(ownerId);
        sb.append(", lowerName=").append(lowerName);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", website=").append(website);
        sb.append(", defaultBranch=").append(defaultBranch);
        sb.append(", size=").append(size);
        sb.append(", useCustomAvatar=").append(useCustomAvatar);
        sb.append(", numWatches=").append(numWatches);
        sb.append(", numStars=").append(numStars);
        sb.append(", numForks=").append(numForks);
        sb.append(", numIssues=").append(numIssues);
        sb.append(", numClosedIssues=").append(numClosedIssues);
        sb.append(", numPulls=").append(numPulls);
        sb.append(", numClosedPulls=").append(numClosedPulls);
        sb.append(", numMilestones=").append(numMilestones);
        sb.append(", numClosedMilestones=").append(numClosedMilestones);
        sb.append(", isPrivate=").append(isPrivate);
        sb.append(", isBare=").append(isBare);
        sb.append(", isMirror=").append(isMirror);
        sb.append(", enableWiki=").append(enableWiki);
        sb.append(", allowPublicWiki=").append(allowPublicWiki);
        sb.append(", enableExternalWiki=").append(enableExternalWiki);
        sb.append(", externalWikiUrl=").append(externalWikiUrl);
        sb.append(", enableIssues=").append(enableIssues);
        sb.append(", allowPublicIssues=").append(allowPublicIssues);
        sb.append(", enableExternalTracker=").append(enableExternalTracker);
        sb.append(", externalTrackerUrl=").append(externalTrackerUrl);
        sb.append(", externalTrackerFormat=").append(externalTrackerFormat);
        sb.append(", externalTrackerStyle=").append(externalTrackerStyle);
        sb.append(", enablePulls=").append(enablePulls);
        sb.append(", pullsIgnoreWhitespace=").append(pullsIgnoreWhitespace);
        sb.append(", pullsAllowRebase=").append(pullsAllowRebase);
        sb.append(", isFork=").append(isFork);
        sb.append(", forkId=").append(forkId);
        sb.append(", createdUnix=").append(createdUnix);
        sb.append(", updatedUnix=").append(updatedUnix);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}