package com.mengka.springboot.model.dto;

import lombok.Data;
import lombok.experimental.Accessors;
import java.io.Serializable;

@Data
@Accessors(chain = true)
public class GogsRepositoryDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.owner_id
     *
     * @mbg.generated
     */
    private Long ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.lower_name
     *
     * @mbg.generated
     */
    private String lowerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.description
     *
     * @mbg.generated
     */
    private String description;

    private Boolean hasChild = false;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.website
     *
     * @mbg.generated
     */
    private String website;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.default_branch
     *
     * @mbg.generated
     */
    private String defaultBranch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.size
     *
     * @mbg.generated
     */
    private Long size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.use_custom_avatar
     *
     * @mbg.generated
     */
    private Boolean useCustomAvatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.num_watches
     *
     * @mbg.generated
     */
    private Integer numWatches;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.num_stars
     *
     * @mbg.generated
     */
    private Integer numStars;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.num_forks
     *
     * @mbg.generated
     */
    private Integer numForks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.num_issues
     *
     * @mbg.generated
     */
    private Integer numIssues;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.num_closed_issues
     *
     * @mbg.generated
     */
    private Integer numClosedIssues;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.num_pulls
     *
     * @mbg.generated
     */
    private Integer numPulls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.num_closed_pulls
     *
     * @mbg.generated
     */
    private Integer numClosedPulls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.num_milestones
     *
     * @mbg.generated
     */
    private Integer numMilestones;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.num_closed_milestones
     *
     * @mbg.generated
     */
    private Integer numClosedMilestones;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.is_private
     *
     * @mbg.generated
     */
    private Boolean isPrivate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.is_bare
     *
     * @mbg.generated
     */
    private Boolean isBare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.is_mirror
     *
     * @mbg.generated
     */
    private Boolean isMirror;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.enable_wiki
     *
     * @mbg.generated
     */
    private Boolean enableWiki;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.allow_public_wiki
     *
     * @mbg.generated
     */
    private Boolean allowPublicWiki;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.enable_external_wiki
     *
     * @mbg.generated
     */
    private Boolean enableExternalWiki;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.external_wiki_url
     *
     * @mbg.generated
     */
    private String externalWikiUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.enable_issues
     *
     * @mbg.generated
     */
    private Boolean enableIssues;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.allow_public_issues
     *
     * @mbg.generated
     */
    private Boolean allowPublicIssues;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.enable_external_tracker
     *
     * @mbg.generated
     */
    private Boolean enableExternalTracker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.external_tracker_url
     *
     * @mbg.generated
     */
    private String externalTrackerUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.external_tracker_format
     *
     * @mbg.generated
     */
    private String externalTrackerFormat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.external_tracker_style
     *
     * @mbg.generated
     */
    private String externalTrackerStyle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.enable_pulls
     *
     * @mbg.generated
     */
    private Boolean enablePulls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.pulls_ignore_whitespace
     *
     * @mbg.generated
     */
    private Boolean pullsIgnoreWhitespace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.pulls_allow_rebase
     *
     * @mbg.generated
     */
    private Boolean pullsAllowRebase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.is_fork
     *
     * @mbg.generated
     */
    private Boolean isFork;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.fork_id
     *
     * @mbg.generated
     */
    private Long forkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.created_unix
     *
     * @mbg.generated
     */
    private Long createdUnix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.updated_unix
     *
     * @mbg.generated
     */
    private Long updatedUnix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table repository
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}
