package com.mengka.springboot.dao.persistence;

import com.mengka.springboot.dao.domain.CommitHistoryDO;
import com.mengka.springboot.dao.domain.CommitHistoryDOKey;
import com.mengka.springboot.dao.domain.RepositoryDO;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface CommitHistoryDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commit_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(CommitHistoryDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commit_history
     *
     * @mbg.generated
     */
    int insert(CommitHistoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commit_history
     *
     * @mbg.generated
     */
    int insertSelective(CommitHistoryDO record);

    /**
     *  批量插入或更新
     *
     * @param list
     * @return
     */
    int batchInsertAndUpdate(@Param("list") List<CommitHistoryDO> list, @Param("updateTime") Date updateTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commit_history
     *
     * @mbg.generated
     */
    CommitHistoryDO selectByPrimaryKey(CommitHistoryDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commit_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CommitHistoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commit_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CommitHistoryDO record);
}