package com.mengka.springboot.dao.persistence;

import com.mengka.springboot.dao.domain.GogsRepositoryDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GogsRepositoryDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbg.generated
     */
    int insert(GogsRepositoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbg.generated
     */
    int insertSelective(GogsRepositoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbg.generated
     */
    GogsRepositoryDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GogsRepositoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GogsRepositoryDO record);

    List<GogsRepositoryDO> selectByBranch(@Param(value = "branch") String branch);
}