package com.mengka.springboot.dao.persistence;

import com.mengka.springboot.dao.domain.RepositoryDO;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

/**
 *  new my DO mapper
 */
public interface RepositoryDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_repository
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_repository
     *
     * @mbg.generated
     */
    int insert(RepositoryDO record);

    /**
     *  批量插入或更新
     *
     * @param list
     * @return
     */
    int batchInsertAndUpdate(@Param("list") List<RepositoryDO> list, @Param("updateTime") Date updateTime);

    RepositoryDO selectByCode(@Param(value = "parentId") Long parentId,@Param(value = "lowerName") String lowerName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_repository
     *
     * @mbg.generated
     */
    int insertSelective(RepositoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_repository
     *
     * @mbg.generated
     */
    RepositoryDO selectByPrimaryKey(Long id);

    List<RepositoryDO> selectByParentId(@Param(value = "parentId") Long parentId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_repository
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RepositoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_repository
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RepositoryDO record);
}